# Generated by Django 3.1.1 on 2020-11-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profilepage', '0002_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(max_length=300),
        ),
    ]
