# Generated by Django 3.1.1 on 2020-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profilepage', '0004_auto_20201129_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.FileField(upload_to='Profile'),
        ),
    ]
