# Generated by Django 3.1.1 on 2020-12-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profilepage', '0005_auto_20201130_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbox',
            name='comment',
            field=models.CharField(max_length=250),
        ),
    ]
