# Generated by Django 3.1.1 on 2020-12-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profilepage', '0007_auto_20201201_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbox',
            name='comment',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.FileField(upload_to='Profiles'),
        ),
    ]
