# Generated by Django 3.1.1 on 2020-12-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profilepage', '0008_auto_20201203_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='default/defaultimg.jpg', upload_to='Profiles'),
        ),
    ]
