# Generated by Django 3.1.1 on 2020-12-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profilepage', '0013_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
