# Generated by Django 3.1.1 on 2020-12-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profilepage', '0015_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
