# Generated by Django 3.1.1 on 2020-12-24 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profilepage', '0016_remove_like_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comm_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profilepage.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Commentbox',
        ),
    ]
